# Generated by Django 3.2.7 on 2021-10-09 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('dirFacturacion', models.CharField(default='-', max_length=100, unique=True, verbose_name='dirFacturacion')),
                ('dirEntrega', models.CharField(default='-', max_length=100, unique=True, verbose_name='dirEntrega')),
                ('ciudad', models.CharField(default='-', max_length=30, verbose_name='Ciudad')),
                ('telefono', models.CharField(default='-', max_length=20, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(unique=True)),
                ('fechaPedido', models.DateTimeField()),
                ('estadoPedido', models.CharField(max_length=30, verbose_name='Estado')),
                ('user_dirEntrega_fk', models.OneToOneField(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='user_dirEntrega', to=settings.AUTH_USER_MODEL, to_field='dirEntrega')),
                ('user_dirFacturacion_fk', models.OneToOneField(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='user_dirFacturacion', to=settings.AUTH_USER_MODEL, to_field='dirFacturacion')),
                ('user_email_fk', models.OneToOneField(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='-', max_length=40, unique=True)),
                ('nombre', models.CharField(default='-', max_length=40)),
                ('precio', models.IntegerField(default=0, unique=True)),
                ('descripcion', models.CharField(default='-', max_length=40)),
                ('miniatura', models.CharField(default='-', max_length=40)),
                ('vencimiento', models.DateTimeField()),
                ('stock', models.IntegerField(default=0)),
                ('imagenes', models.CharField(default='-', max_length=40)),
                ('categoria', models.CharField(default='-', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orders_cantidad_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders_cantidad.set()+', to='authApp.orders', to_field='cantidad')),
                ('orders_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_id.set()+', to='authApp.orders')),
                ('products_codigo_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products_codigo.set()+', to='authApp.products', to_field='codigo')),
                ('products_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_id.set()+', to='authApp.products')),
                ('products_precio_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products_precio.set()+', to='authApp.products', to_field='precio')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('lastChangeDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
