# Generated by Django 3.2.7 on 2021-10-05 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='usuario_ciudad',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='usuario_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='usuario_id',
        ),
        migrations.AddField(
            model_name='user',
            name='usuario_contrasenha',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usuario_nombre',
            field=models.CharField(default='.', max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usuario_telefono',
            field=models.CharField(default='-', max_length=20, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('orden_id', models.AutoField(primary_key=True, serialize=False)),
                ('orden_cantidad', models.IntegerField()),
                ('orden_fechaPedido', models.DateTimeField()),
                ('orden_estadoPedido', models.CharField(max_length=30, verbose_name='Estado')),
                ('usuario_correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_correo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Orden',
            fields=[
                ('detallesOrden_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_codigo_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_codigo', to='authApp.productos')),
            ],
        ),
    ]
